name: Validate Renovate presets

on:
  workflow_dispatch:
  push:
    paths:
      - "default.json"
      - "go.json"
      - "renovate.json"
      - ".forgejo/workflows/validate.yml"
  pull_request:
    paths:
      - "default.json"
      - "go.json"
      - "renovate.json"
      - ".forgejo/workflows/validate.yml"

permissions:
  contents: read

jobs:
  validate:
    name: renovate-config-validator
    runs-on: ha
    container:
      image: ghcr.io/renovatebot/renovate:44.126.0@sha256:b07b6fe34bd80fe2ce035e2053d63a0205e5f99ba3ee799447e0439f2c728002
      options: --tmpfs /tmp:exec
    steps:
      - name: Checkout
        uses: https://git.xlion.tw/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate repository config and presets
        run: >-
          renovate-config-validator
          --strict
          --no-global
          renovate.json
          default.json
          go.json
