name: Validate Renovate presets

on:
  workflow_dispatch:
  push:
    paths:
      - "default.json"
      - "go.json"
      - "renovate.json"
      - ".forgejo/workflows/validate.yml"
  pull_request:
    paths:
      - "default.json"
      - "go.json"
      - "renovate.json"
      - ".forgejo/workflows/validate.yml"

permissions:
  contents: read

jobs:
  validate:
    name: renovate-config-validator
    runs-on: ha
    container:
      image: ghcr.io/renovatebot/renovate:44.46.4@sha256:3b64619da15eec8cc7eb7e422698736d6e129bf0832e8b90fe956706cde3c133
      options: --tmpfs /tmp:exec
    steps:
      - name: Checkout
        uses: https://git.xlion.tw/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate repository config and presets
        run: >-
          renovate-config-validator
          --strict
          --no-global
          renovate.json
          default.json
          go.json
