name: Validate Renovate presets

on:
  workflow_dispatch:
  push:
    paths:
      - "default.json"
      - "go.json"
      - "renovate.json"
      - ".forgejo/workflows/validate.yml"
  pull_request:
    paths:
      - "default.json"
      - "go.json"
      - "renovate.json"
      - ".forgejo/workflows/validate.yml"

permissions:
  contents: read

jobs:
  validate:
    name: renovate-config-validator
    runs-on: ha
    container:
      image: ghcr.io/renovatebot/renovate:44.33.2@sha256:fe47c58a918726ecb9efa7837735e2a7c6eed44e0181ab2c7b14738b84df0a21
      options: --tmpfs /tmp:exec
    steps:
      - name: Checkout
        uses: https://git.xlion.tw/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate repository config and presets
        run: >-
          renovate-config-validator
          --strict
          --no-global
          renovate.json
          default.json
          go.json
